### ISSUE TITLE
Gramps 6.0 testing - Cardview does not load - "cannot import name 'to_json' from 'gramps.gen.lib.serialize'"

### ISSUE THREAD

**Issue by wroldwiedbwe** [cdhorn/CardView#247]
Changed reference to "5.2" (.gpr.py files) and changed them to 6.0 and Cardview does not work in 6.0.

What are your plans for Cardview?

Love for Cardview to be updated 😊 if you have time?

2025-03-31 07:42:07.578: WARNING: _manager.py: line 328: Plugin error (from 'status_person'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:07.592: WARNING: _manager.py: line 328: Plugin error (from 'status_todo'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:08.502: WARNING: _manager.py: line 328: Plugin error (from 'card_view_person'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:12.539: WARNING: _manager.py: line 328: Plugin error (from 'card_view_person'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:12.541: WARNING: _manager.py: line 328: Plugin error (from 'card_view_person'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:13.567: WARNING: _manager.py: line 328: Plugin error (from 'card_view_family'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:14.225: WARNING: _manager.py: line 328: Plugin error (from 'card_view_event'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:15.056: WARNING: _manager.py: line 328: Plugin error (from 'card_view_place'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:15.728: WARNING: _manager.py: line 328: Plugin error (from 'card_view_source'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:16.299: WARNING: _manager.py: line 328: Plugin error (from 'card_view_citation'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:16.911: WARNING: _manager.py: line 328: Plugin error (from 'card_view_repository'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:17.712: WARNING: _manager.py: line 328: Plugin error (from 'card_view_media'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:18.313: WARNING: _manager.py: line 328: Plugin error (from 'card_view_note'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:18.928: WARNING: _manager.py: line 328: Plugin error (from 'card_view_tag'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)
2025-03-31 07:42:19.445: WARNING: _manager.py: line 328: Plugin error (from 'tagview'): cannot import name 'to_json' from 'gramps.gen.lib.serialize' (C:\Program Files\GrampsAIO64-6.0.0\gramps\gen\lib\serialize.py)

Same error message as on Gramps issue [13710](https://gramps-project.org/bugs/view.php?id=13710) for the JSONExport addon.

**Comment by cdhorn** [comment]
Yes, this is to be expected.

I will try to make some time to fix this.

**Comment by fxtmtrsine** [comment]
> Same error message as on Gramps issue [13710](https://gramps-project.org/bugs/view.php?id=13710) for the JSONExport addon.

if it helps the pr for that issue.
https://github.com/gramps-project/addons-source/pull/732

**Comment by GaryGriffin** [comment]
I think this is a more compact set of changes to address this

https://github.com/gramps-project/addons-source/pull/731/commits/0f8446c2a1dd97f031c564b3e4fcac6e23f7c3d7

**Comment by cdhorn** [comment]
Sorry forgot about this, on quit the hiatus from genealogy related stuff so thanks for the reminder. No real testing yet, and I'll be out good portion of the rest of the day, but pushed the changes needed for it to load under 6.0.

**Comment by giotodibondone** [comment]
_ERROR: Plugin file C:\Users\gioto\AppData\Roaming\gramps\gramps60\plugins\CardView-master\src\template_minimal.py has a version of "5.2" which is invalid for Gramps "AIO64-6.0.1--1"._

**Comment by cdhorn** [comment]
Oops, sorry, got that one too now.

**Comment by wroldwiedbwe** [comment]
@cdhorn [Thank you](https://github.com/cdhorn/CardView/commit/f1d328038ab2b580e9b4bd32cd3d78628e9241dc)

**Comment by cdhorn** [comment]
You are most welcome. Really need to make some time to pivot back to this. Maybe this coming winter, don't see it happening in next few months for sure.

**Comment by sam-m888** [comment]
Thank you
